name: stateful_books
description: go_router books example, with stateful nested navigation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  collection: ^1.18.0
  adaptive_navigation: ^0.0.10
  go_router: ^14.2.7

  result_notifier: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
